import vgamepad


d = vgamepad.DS4_BUTTONS


keymaps = [
    d.DS4_BUTTON_CROSS,
    d.DS4_BUTTON_CIRCLE,
    d.DS4_BUTTON_SQUARE,
    d.DS4_BUTTON_TRIANGLE,
    d.DS4_BUTTON_SHARE,
    vgamepad.DS4_SPECIAL_BUTTONS.DS4_SPECIAL_BUTTON_PS,
    d.DS4_BUTTON_OPTIONS,
    d.DS4_BUTTON_THUMB_LEFT,
    d.DS4_BUTTON_THUMB_RIGHT,
    d.DS4_BUTTON_SHOULDER_LEFT,
    d.DS4_BUTTON_SHOULDER_RIGHT,
    vgamepad.DS4_DPAD_DIRECTIONS.DS4_BUTTON_DPAD_NORTH,
    vgamepad.DS4_DPAD_DIRECTIONS.DS4_BUTTON_DPAD_SOUTH,
    vgamepad.DS4_DPAD_DIRECTIONS.DS4_BUTTON_DPAD_WEST,
    vgamepad.DS4_DPAD_DIRECTIONS.DS4_BUTTON_DPAD_EAST,
    vgamepad.DS4_SPECIAL_BUTTONS.DS4_SPECIAL_BUTTON_TOUCHPAD,
]